//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HANG_HOA
    {
        public decimal ID { get; set; }
        public decimal ID_LOAI_HANG { get; set; }
        public string T7_CN { get; set; }
        public System.DateTime NGAY_LUU_HANH { get; set; }
        public string GIA { get; set; }
    
        public virtual DM_LOAI_HANG DM_LOAI_HANG { get; set; }
    }
}
