//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHU_SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_KHU_SAN()
        {
            this.DM_LOAI_HANG = new HashSet<DM_LOAI_HANG>();
            this.DM_PHAN_QUYEN = new HashSet<DM_PHAN_QUYEN>();
            this.DM_SAN = new HashSet<DM_SAN>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_QUAN { get; set; }
        public string TEN_KHU_SAN { get; set; }
        public string DIA_CHI { get; set; }
        public string SO_DIEN_THOAI { get; set; }
    
        public virtual DM_QUAN DM_QUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_LOAI_HANG> DM_LOAI_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PHAN_QUYEN> DM_PHAN_QUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_SAN> DM_SAN { get; set; }
    }
}
