//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LOAI_HANG()
        {
            this.DM_HANG_HOA = new HashSet<DM_HANG_HOA>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_KHU_SAN { get; set; }
        public string GIO_BAT_DAU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_HANG_HOA> DM_HANG_HOA { get; set; }
        public virtual DM_KHU_SAN DM_KHU_SAN { get; set; }
    }
}
