//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHAN_QUYEN
    {
        public decimal ID { get; set; }
        public decimal ID_TAI_KHOAN { get; set; }
        public decimal ID_KHU_SAN { get; set; }
    
        public virtual DM_KHU_SAN DM_KHU_SAN { get; set; }
        public virtual DM_TAI_KHOAN DM_TAI_KHOAN { get; set; }
    }
}
