//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_SAN()
        {
            this.GD_HOP_DONG_CHI_TIET = new HashSet<GD_HOP_DONG_CHI_TIET>();
            this.GD_PHIEU_DAT_SAN_CHI_TIET = new HashSet<GD_PHIEU_DAT_SAN_CHI_TIET>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_KHU_SAN { get; set; }
        public string TEN_SAN { get; set; }
    
        public virtual DM_KHU_SAN DM_KHU_SAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_HOP_DONG_CHI_TIET> GD_HOP_DONG_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_PHIEU_DAT_SAN_CHI_TIET> GD_PHIEU_DAT_SAN_CHI_TIET { get; set; }
    }
}
