//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TAI_KHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_TAI_KHOAN()
        {
            this.DM_PHAN_QUYEN = new HashSet<DM_PHAN_QUYEN>();
        }
    
        public decimal ID { get; set; }
        public string TEN_TAI_KHOAN { get; set; }
        public string MAT_KHAU { get; set; }
        public string TEN_NGUOI_DUNG { get; set; }
        public string SO_DIEN_THOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_PHAN_QUYEN> DM_PHAN_QUYEN { get; set; }
    }
}
