//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_HOP_DONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_HOP_DONG()
        {
            this.GD_HOP_DONG_CHI_TIET = new HashSet<GD_HOP_DONG_CHI_TIET>();
        }
    
        public decimal ID { get; set; }
        public string MA_HOP_DONG { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public System.DateTime NGAY_BAT_DAU { get; set; }
        public System.DateTime NGAY_KET_THUC { get; set; }
        public string DAT_COC { get; set; }
        public System.DateTime NGAY_THANH_TOAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_HOP_DONG_CHI_TIET> GD_HOP_DONG_CHI_TIET { get; set; }
    }
}
