//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_PHIEU_DAT_SAN_CHI_TIET
    {
        public decimal ID { get; set; }
        public decimal ID_PHIEU { get; set; }
        public decimal ID_KHUNG_GIO { get; set; }
        public decimal ID_SAN { get; set; }
        public string GIA { get; set; }
        public string DAT_COC { get; set; }
        public string DA_THANH_TOAN { get; set; }
        public string HUY_SAN { get; set; }
    
        public virtual DM_KHUNG_GIO DM_KHUNG_GIO { get; set; }
        public virtual DM_SAN DM_SAN { get; set; }
        public virtual GD_PHIEU_DAT_SAN GD_PHIEU_DAT_SAN { get; set; }
    }
}
