//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_PHIEU_DAT_SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_PHIEU_DAT_SAN()
        {
            this.GD_PHIEU_DAT_SAN_CHI_TIET = new HashSet<GD_PHIEU_DAT_SAN_CHI_TIET>();
        }
    
        public decimal ID { get; set; }
        public string MA_PHIEU { get; set; }
        public System.DateTime NGAY_DAT { get; set; }
        public System.DateTime NGAY_DA { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string SO_DIEN_THOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_PHIEU_DAT_SAN_CHI_TIET> GD_PHIEU_DAT_SAN_CHI_TIET { get; set; }
    }
}
