//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9EEDEC_QLSBEntities : DbContext
    {
        public DB_9EEDEC_QLSBEntities()
            : base("name=DB_9EEDEC_QLSBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_HANG_HOA> DM_HANG_HOA { get; set; }
        public virtual DbSet<DM_KHU_SAN> DM_KHU_SAN { get; set; }
        public virtual DbSet<DM_KHUNG_GIO> DM_KHUNG_GIO { get; set; }
        public virtual DbSet<DM_LOAI_HANG> DM_LOAI_HANG { get; set; }
        public virtual DbSet<DM_PHAN_QUYEN> DM_PHAN_QUYEN { get; set; }
        public virtual DbSet<DM_QUAN> DM_QUAN { get; set; }
        public virtual DbSet<DM_SAN> DM_SAN { get; set; }
        public virtual DbSet<DM_TAI_KHOAN> DM_TAI_KHOAN { get; set; }
        public virtual DbSet<DM_THANH_PHO> DM_THANH_PHO { get; set; }
        public virtual DbSet<GD_HOP_DONG> GD_HOP_DONG { get; set; }
        public virtual DbSet<GD_HOP_DONG_CHI_TIET> GD_HOP_DONG_CHI_TIET { get; set; }
        public virtual DbSet<GD_PHIEU_DAT_SAN> GD_PHIEU_DAT_SAN { get; set; }
        public virtual DbSet<GD_PHIEU_DAT_SAN_CHI_TIET> GD_PHIEU_DAT_SAN_CHI_TIET { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
